version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 954976317673.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t loginpage .
      - docker tag loginpage:latest 954976317673.dkr.ecr.eu-north-1.amazonaws.com/loginpage:latest
  post_build:
    commands:
      - echo "Building Docker image..."
      - docker build -t loginpage .
      - echo "Tagging Docker image..."
      - docker tag loginpage:latest 954976317673.dkr.ecr.eu-north-1.amazonaws.com/loginpage:latest
      - echo "Listing Docker images to confirm tag..."
      - docker images

artifacts:
  files:
    - imagedefinitions.json
